name: PR Checks

on:
  pull_request:
    branches:
      - main # Or whatever your default branch is (e.g., master, develop)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Or your desired Java version
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check
        # This task checks for formatting violations.
        # It will fail the build if any files are not formatted correctly.
        run: ./gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew test